name: samskara
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.PNG
    - assets/Splash.PNG
    - assets/google_logo.png
    - assets/IOSlogo.png
    - .env

flutter_native_splash:
  color: "#F8F4E9"

  image: assets/Splash.PNG
  fullscreen: true

  ios: true
  android: false

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: assets/Logo.PNG
  image_path_ios: assets/IOSlogo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#F8F4E9"
  adaptive_icon_foreground: assets/IOSlogo.png